spring.application.name=actividad3

spring.datasource.url=jdbc:mysql://testing-testingjp.a.aivencloud.com:13183/defaultdb
spring.datasource.username=${DB_USER:devuser}
spring.datasource.password={DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
# 'update': crea o actualiza las tablas sin borrar datos existentes
# 'validate': solo verifica que las tablas coincidan con las entidades
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola para depuración
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto para MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect